config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :admin do
    #get :eposnow, to: 'eposnow#index'
    #scope module: :eposnow do
    #  resources 'Eposnow::Customer'
    #resources [:eposnow, :customers]
    #end
    namespace :eposnow do
    #scope module: :eposnow do #, as: 'admin_eposnow' do
      resources :categories, only: [:index] do
        collection do
          post :sync
        end
      end
      resources :customers, except: [:destroy]
      resources :product_stocks, except: [:destroy] do
        collection do
          post :sync_all
        end
      end
      resources :locations, except: [:destroy] do
        member do 
          post :link
        end
      end
      resources :products, only: [:index, :show, :new, :create] do
        member do
          patch :sync
        end
        collection do
          post :sync_all
        end
      end
    end

    resource :eposnow, only: [:update, :edit] do
      get 'products/:id', to: 'eposnows#product', as: :product
      collection do
        #get :products
        get :transactions
        get :staff
      end
    end
  end

end

app/models/spree/epos_now.rb
# encoding: UTF-8
require 'httparty'

class Spree::EposNow
  include HTTParty

  base_uri 'https://api.eposnowhq.com'
  headers "Content-Type" => "application/json"

  basic_auth Spree::Config[:eposnow_key], Spree::Config[:eposnow_secret]

  if Rails.env == 'development'
    debug_output $stdout
  end

  # def self.product(id)
  #   self.get('/api/V2/Product/'+id.to_s)
  # end

  # def self.customers
  #   #https://api.eposnowhq.com/api/V2/Customer?page=
  #   self.get('/api/V2/Customer', { query: { page: 1} } )
  # end
  
end

app/models/spree/eposnow/category.rb
# encoding: UTF-8
require 'httparty'
module Spree
  
  class Eposnow::Category #< ActiveResource::Base
    include ActiveModel::Model
    #self.site = "https://api.eposnowhq.com"
    include HTTParty

    base_uri 'https://api.eposnowhq.com'
    headers "Content-Type" => "application/json"

    basic_auth Spree::Config[:eposnow_key], Spree::Config[:eposnow_secret]

    if Rails.env == 'development'
      debug_output $stdout
    end  
    
    #attr_accessor   


    def self.all
      self.get('/api/V2/Category')
    end

  end

end

app/models/spree/eposnow/customer.rb
# encoding: UTF-8
require 'httparty'
module Spree
  
  class Eposnow::Customer #< ActiveResource::Base
    include ActiveModel::Model
    #self.site = "https://api.eposnowhq.com"
    include HTTParty

    base_uri 'https://api.eposnowhq.com'
    headers "Content-Type" => "application/json"

    basic_auth Spree::Config[:eposnow_key], Spree::Config[:eposnow_secret]

    if Rails.env == 'development'
      debug_output $stdout
    end  
    
    attr_accessor   :Title, :Forename, :Surname, :BusinessName, :DateOfBirth, :MainAddressID,
                    :ContactNumber, :ContactNumber2, :EmailAddress, :Type,
                    :MaxCredit, :CurrentBalance, :CurrentBalance, :ExpiryDate,
                    :CardNumber, :CurrentPoints, :SignUpDate, :Notes, :CustomerID,
                    :SignUpLocationID

    def self.create(attrs = {})
      self.post(
        '/api/V2/Customer/', 
        {
          :body => { 
            :Title => 0,
            :Forename => "Mr Ex",
            :Surname => "Pired" ,
            :BusinessName => nil,
            :DateOfBirth => nil,
            :MainAddressID => 1,
            :ContactNumber => "09876543987",
            :ContactNumber2 => "98765439876",
            :EmailAddress => "made@up.com",
            :Type => 4187,
            :MaxCredit => 0,
            :CurrentBalance => 0,
            :ExpiryDate => "2013-01-17T00:00:00",
            :CardNumber => "%0003?;1236?",
            :CurrentPoints => 0,
            :SignUpDate => "2013-03-12T11:40:49.323",
            :Notes => nil
          }.to_json
        }
      )
    end

    def self.paginate(page_no = 1)
      self.get(
        '/api/V2/Customer',
        { query: { page: page_no } } 
      ).collect { |x| self.new(x) } 
    end    

  end

end

app/models/spree/eposnow/customer_type.rb
# encoding: UTF-8
require 'httparty'

module Spree

  class Eposnow::CustomerType #< ActiveResource::Base
    include ActiveModel::Model
    #self.site = "https://api.eposnowhq.com"
    include HTTParty

    base_uri 'https://api.eposnowhq.com'
    headers "Content-Type" => "application/json"

    basic_auth Spree::Config[:eposnow_key], Spree::Config[:eposnow_secret]    

    def self.all
      #https://api.eposnowhq.com/api/V2/CustomerType/
      self.get('/api/V2/CustomerType')
    end

  end

end

app/models/spree/eposnow/location.rb
# encoding: UTF-8
require 'httparty'
module Spree
  
  class Eposnow::Location #< ActiveResource::Base
    include ActiveModel::Model
    #self.site = "https://api.eposnowhq.com"
    include HTTParty

    base_uri 'https://api.eposnowhq.com'
    headers "Content-Type" => "application/json"

    basic_auth Spree::Config[:eposnow_key], Spree::Config[:eposnow_secret]

    if Rails.env == 'development'
      debug_output $stdout
    end

    attr_accessor   :LocationID, :LocationAreaID, :Name, :BusinessName, :Description,
                    :Address1, :Address2, :Town, :County, :PostCode, :EmailAddress

    def self.all
      self.get('/api/V2/Location')
    end

    def self.find(id)
      self.get('/api/V2/Location/'+id)
    end

  end

end

app/models/spree/eposnow/product_stock.rb
# encoding: UTF-8
require 'httparty'
module Spree
  
  class Eposnow::ProductStock #< ActiveResource::Base
    include ActiveModel::Model
    #self.site = "https://api.eposnowhq.com"
    include HTTParty

    base_uri 'https://api.eposnowhq.com'
    headers "Content-Type" => "application/json"

    basic_auth Spree::Config[:eposnow_key], Spree::Config[:eposnow_secret]

    if Rails.env == 'development'
      debug_output $stdout
    end

    attr_accessor   :StockID, :LocationID, :ProductID, :CurrentStock, :MinStock,
                    :MaxStock, :CurrentVolume, :OnOrder, :Alerts, :CostPrice

    def self.paginate(page_no = 1)
      self.get(
        '/api/V2/ProductStock/',
        { query: { page: page_no } } 
      )
      #https://api.eposnowhq.com/api/V2/ProductStock?page={Page_No}
    end

    def self.find(id)
      response = self.get('/api/V2/ProductStock/'+id )
      self.new response.to_hash
    end

    def update(attr = {})
      response = self.class.put(
        '/api/V2/ProductStock/'+self.StockID.to_s,
        {
          :body => attr.to_json
        }        
      )
    end

    def set_count_on_hand(count_on_hand)
      update( { 'CurrentStock' => count_on_hand } )
    end

    def self.index_keys
      keys - [:StockID]
    end

    def self.keys
      [
        :StockID, :LocationID, :Product, :CurrentStock, :MinStock,
        :MaxStock, :CurrentVolume, :OnOrder, :Alerts, :CostPrice
      ]      
    end

    def keys
      [
        :StockID, :LocationID, :ProductID, :CurrentStock, :MinStock,
        :MaxStock, :CurrentVolume, :OnOrder, :Alerts, :CostPrice
      ]
    end

  end
end

app/controllers/spree/admin/eposnow/categories_controller.rb
module Spree
  module Admin
    module Eposnow
      class CategoriesController < Spree::Admin::BaseController

        MAPPING = {
          "Name" => :name,
          "Description" => :description,
          "CategoryID" => :eposnow_category_id
        }

        def index
          @categories = Spree::Eposnow::Category.all
          # @categories =  Spree::EposNow.customers.collect do |x| 
          #                 x.slice("Forename", "Surname", "EmailAddress", "ContactNumber")
          #               end          
        end

        def sync
          create_count = 0
          root_category = Spree::Taxonomy.where(name: 'Categories').first_or_create
          root_taxon_category = Spree::Taxon.where(name: 'Categories').first
          Spree::Eposnow::Category.all.each do |category|
            taxon = Spree::Taxon.where(name: category['Name']).first_or_initialize
            attributes = Hash[*MAPPING.collect { |key,value| [value, category[key]] }.flatten]
            attributes[:taxonomy] = root_category
            unless category['ParentID'].nil?
              attributes[:parent] = Spree::Taxon.find_by_eposnow_category_id(category['ParentID'])
            else
              attributes[:parent] = root_taxon_category
            end
            if attributes[:parent] && taxon.update_attributes(attributes)
              create_count += 1
            end
          end
          flash[:success] = "#{create_count} categories sync'd"
          return redirect_to admin_eposnow_categories_path
        end

      end

    end

  end

end

# * Kitchen Bed & Bath  
# * Gifts Jewellery & Stationery
# * Delivery
# * Home Accessories
# * Lighting
# * Furniture

# {"CategoryID"=>72656,
#  "Name"=>"Food",
#  "Description"=>"FoodCat",
#  "ParentID"=>nil,
#  "ShowOnTill"=>true,
#  "Wet"=>false,
#  "ButtonColourID"=>nil,
#  "SortPosition"=>nil,
#  "ReportingCategoryID"=>nil,
#  "NominalCode"=>nil}

app/controllers/spree/admin/eposnow/customers_controller.rb
module Spree
  module Admin
    module Eposnow
      class CustomersController < Spree::Admin::BaseController

        def new
          @customer = Spree::Eposnow::Customer.new
        end

        def index
          @customers =  Spree::Eposnow::Customer.paginate
          # @customers =  Spree::Eposnow::Customer.paginate.collect do |x| 
          #                 x.slice("Forename", "Surname", "EmailAddress", "ContactNumber")
          #               end          
        end

        def create
          response = Spree::Eposnow::Customer.create(params[:admin_eposnow_customer])
          if response.code == 201
            return redirect_to admin_eposnow_customers_path
          end
          @customer = Spree::Eposnow::Customer.new(params[:admin_eposnow_customer])
          @customer.errors.add(:base, response.to_s)
          return render :new          
        end

      end

    end

  end

end

app/controllers/spree/admin/eposnow/eposnow_products_controller.rb
module Spree
  module Admin
    module Eposnow
      class EposnowProductsController < Spree::Admin::BaseController

        def index
          params[:page] ||= 1
          @products = Spree::Eposnow::Product.paginate(params[:page])
        end

        # def link
        #   @location = Spree::Eposnow::Location.find(params[:id])
        #   stock_location = Spree::StockLocation.find(params[:location_id])
        #   stock_location.eposnow_location_id = @location['LocationID']
        #   stock_location.save
        #   return redirect_to admin_eposnow_locations_path
        # end

        def show
          @product = Spree::Eposnow::Product.find(params[:id])
        end

        def sync
          @product = Spree::Eposnow::Product.find(params[:id])
          @product.sync
          return redirect_to admin_eposnow_eposnow_product_path(params[:id])
        end

        def sync_all
          page = 1
          @products = Spree::Eposnow::Product.paginate(page)
          product_count = 0
          begin
            @products.each do |x|
              product = Spree::Eposnow::Product.find(x['ProductID'].to_s)
              product.sync
              product_count += 1
            end
            page += 1
            @products = Spree::Eposnow::Product.paginate(page)
          end until @products.length < 200

        end

      end
    end
  end
end

app/controllers/spree/admin/eposnow/locations_controller.rb
module Spree
  module Admin
    module Eposnow
      class LocationsController < Spree::Admin::BaseController

        def index
          @locations = Spree::Eposnow::Location.all
        end

        def edit
          @location = Spree::Eposnow::Location.find(params[:id])
          @stock_location = Spree::StockLocation.where(eposnow_location_id: params[:id]).first_or_initialize
          #https://api.eposnowhq.com/api/V2/Location/{Location_ID}
        end

        def link
          @location = Spree::Eposnow::Location.find(params[:id])
          stock_location = Spree::StockLocation.find(params[:location_id])
          stock_location.eposnow_location_id = @location['LocationID']
          stock_location.save
          return redirect_to admin_eposnow_locations_path
        end

      end

    end

  end

end

app/controllers/spree/admin/eposnow/product_stocks_controller.rb
module Spree
  module Admin
    module Eposnow
      class ProductStocksController < Spree::Admin::BaseController

        def index
          params[:page] ||= 1
          @product_stocks = Spree::Eposnow::ProductStock.paginate(params[:page])
        end

        def edit
          @product_stock = Spree::Eposnow::ProductStock.find(params[:id])
          @variant = Spree::Variant.find_by_eposnow_product_id(@product_stock.ProductID)
          @stock_location = @variant.stock_locations.where(eposnow_location_id: @product_stock.LocationID)
        end

        def update
          @product_stock = Spree::Eposnow::ProductStock.find(params[:id])
          @product_stock.update( params[:eposnow_product_stock] )
          return redirect_to edit_admin_eposnow_product_stock_path( params[:id] )
        end

        def sync_all

          # TODO This is duplicated with the sync RakeTask
          link_with_eposnow

          @product_stocks = Spree::Eposnow::ProductStock.paginate(1)
          
          @product_stocks.each do |product_stock|
            
            variant = Spree::Variant.find_by_eposnow_product_id(product_stock['ProductID'])
            next unless variant
            stock_location = variant.stock_locations.where(eposnow_location_id: product_stock['LocationID']).first
            next unless stock_location
            # Spree::StockItem
            stock_item = stock_location.stock_items.where(variant:variant).first_or_initialize

            stock_item.eposnow_product_stock_id = product_stock['StockID']
            stock_item.set_count_on_hand product_stock['CurrentStock'] >= 0 ? product_stock['CurrentStock'] : 0
          end
          return redirect_to admin_eposnow_product_stocks_path
        end

      protected

        def link_with_eposnow
          results = []
          page = 1
          until (@products = Spree::Eposnow::Product.paginate(page)).empty?
            @products.each do |x|
              sku = x.Barcode
              next if sku.nil?
              next if sku.blank?
              v = Spree::Variant.find_by_sku(sku)
              next if v.nil?
              if v.eposnow_product_id.nil?
                product_id = x.ProductID.to_i
                v.eposnow_product_id = product_id
                v.save
                results << v.product.name
              end
            end  
            page +=1
          end
        end        

      end

    end
    
  end

end

app/controllers/spree/admin/eposnow/products_controller.rb
module Spree
  module Admin
    module Eposnow
      class ProductsController < Spree::Admin::BaseController

        def index
          params[:page] ||= 1
          @products = Spree::Eposnow::Product.paginate(params[:page])
        end

        # def link
        #   @location = Spree::Eposnow::Location.find(params[:id])
        #   stock_location = Spree::StockLocation.find(params[:location_id])
        #   stock_location.eposnow_location_id = @location['LocationID']
        #   stock_location.save
        #   return redirect_to admin_eposnow_locations_path
        # end

        def show
          @product = Spree::Eposnow::Product.find(params[:id])
          @variant = Spree::Variant.where(eposnow_product_id: @product.ProductID).first
        end

        def new
          @product = Spree::Eposnow::Product.new
        end

        def create
          @product = Spree::Eposnow::Product.new(params[:eposnow_product])
          if @product.create
            return redirect_to admin_eposnow_products_path
          else
            return render :new
          end
        end

        def sync
          @product = Spree::Eposnow::Product.find(params[:id])
          @product.sync
          return redirect_to admin_eposnow_product_path(params[:id])
        end

        def sync_all
          page = 1
          @products = Spree::Eposnow::Product.paginate(page)
          product_count = 0
          begin
            @products.each do |x|
              product = Spree::Eposnow::Product.find(x['ProductID'].to_s)
              product.sync
              product_count += 1
            end
            page += 1
            @products = Spree::Eposnow::Product.paginate(page)
          end until @products.length < 200

        end

      end
    end
  end
end

app/controllers/spree/admin/eposnows_controller.rb
class Spree::Admin::EposnowsController < Spree::Admin::BaseController

  def edit
  end

  # # https://api.eposnowhq.com/api/V2/Product/{Product_ID}
  # def product
  #   @product = Spree::EposNow.product(params[:id])    
  # end

  def update
    params.each do |name, value|
      next unless Spree::Config.has_preference? name
      Spree::Config[name] = value
    end
    flash[:success] = Spree.t(:successfully_updated, resource: 'Epos Now Settings')    
    redirect_to edit_admin_eposnow_url
  end

  # # http://developer.eposnowhq.com/Docs/Product
  # # GET https://api.eposnowhq.com/api/V2/Product?page={Page_No}

  # def products
  #   @products = Spree::EposNow.products.collect do |x| 
  #                 x.slice("Name", "Description", "Sku", "ProductID")
  #               end
  # end

end

app/helpers/spree/admin/eposnow/customers_helper.rb
module Spree::Admin::Eposnow::CustomersHelper
end

app/helpers/spree/admin/eposnow_helper.rb
module Spree::Admin::EposnowHelper
end

app/views/spree/admin/eposnows/customers.html.erb
<% content_for :page_title do %>
  <%# Spree.t(:eposnow_products) %> <%# TODO Change to variants %>
  Epos Now Customers
<% end %>

<div class='row'>

  <div class="col-md-12">
    <table class='table'>
      <thead>
        <tr>
          <% @customers.first.keys.each do |x| %>
            <th><%= x %></th>
          <% end %>
          <th><%= ' ' %></th>
        </tr>  
      </thead>
      <tbody>
        <% @customers.each do |x| %>
          <tr>
            <% x.values.each do |y| %>
              <td><%= y %></td>
            <% end %>
            <td>
              <%# link_to_edit_url(
                    product_admin_eposnow_path(x['ProductID']),
                    :no_text => true
                  )
              %>
            </td>            
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/spree/admin/eposnows/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:eposnow) %>
<% end %>

  <div id="preferences" data-hook>

    <fieldset class="general no-border-top">

      <%# fields_for :eposnow do |f| %>
        <div class="row">
          <div class="col-md-6">

            <div class="panel panel-default documentation">
              <div class="panel-heading">
                <h1 class="panel-title">
                  Support
                </h1>
              </div>

              <div class="panel-body">
                <%= link_to 'Documentation', 
                            'http://developer.eposnowhq.com/Docs/Documentation' 
                %>
              </div>
            </div>

            <!-- <div class="form-group" data-hook="admin_general_setting_api_key"> -->

            <%= form_tag admin_eposnow_path, method: :put do |f| %>
              <div class="form-group">
                <%= label_tag :eposnow_key %>
                <%= text_field_tag  :eposnow_key, 
                                    Spree::Config[:eposnow_key], 
                                    class: 'form-control' 
                %>
              </div>

              <div class="form-group">
                <%= label_tag :eposnow_secret %>
                <%= text_field_tag  :eposnow_secret, 
                                    Spree::Config[:eposnow_secret], 
                                    class: 'form-control'  
                %>
              </div>

              <div class="form-actions" data-hook="buttons">
                <%= button Spree.t('actions.update'), 'save' %>
                <span class="or"><%= Spree.t(:or) %></span>
                <%= button_link_to  Spree.t('actions.cancel'), 
                                    edit_admin_general_settings_url, icon: 'delete' 
                %>
              </div>

            <% end %> 
          
          </div>

          <div class="col-md-6">

            <aside data-hook="" class="main-right-sidebar" id="sidebar">
              <ul data-hook="admin_product_tabs" class="nav nav-pills nav-stacked">
              
                <li>
                  <%= link_to 'Products', admin_eposnow_products_path %>
                </li>
                <li>
                  <%= link_to 'Categories', admin_eposnow_categories_path %>
                </li>                
                <li>
                  <%= link_to 'Customers', admin_eposnow_customers_path %>
                </li>
                <li>
                  <%= link_to 'StockControls', admin_eposnow_product_stocks_path %>
                </li>
                <li>
                  <%= link_to 'Locations', admin_eposnow_locations_path %>
                </li>                
                <li>
                  <%= link_to 'Transactions', transactions_admin_eposnow_path %>
                </li>
                <li>
                  <%= link_to 'Staff', staff_admin_eposnow_path %>
                </li>                                                            
              </ul> 

            </aside>             

          </div>        

        </div>

    </fieldset>

  </div>

app/views/spree/admin/eposnows/products.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:eposnow_products) %> <%# TODO Change to variants %>
<% end %>

<div class='row'>

  <div class="col-md-12">
    <table class='table'>
      <thead>
        <tr>
          <% @products.first.keys.each do |x| %>
            <th><%= x %></th>
          <% end %>
          <th><%= ' ' %></th>
        </tr>  
      </thead>
      <tbody>
        <% @products.each do |x| %>
          <tr>
            <% x.values.each do |y| %>
              <td><%= y %></td>
            <% end %>
            <td>
              <%= link_to_edit_url(
                    product_admin_eposnow_path(x['ProductID']),
                    :no_text => true
                  )
              %>
            </td>            
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>